<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
﻿<!-- 更换头像模态框 -->
﻿<div id="md_changeImg" class="modal fade" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content" style="width:360px">
      <div class="modal-header">
        <h5 id="md_changeImg_title" class="modal-title">更换头像</h5>
      </div>
      
      <div class="modal-body" style="height:200px;">
        
      </div>
      
      <div class="modal-footer">
        <a id="a_choiceImg" class="btn btn-info btn-sm" href="javascript:void(0)" style="width:80px"><span class="icon-document-checked"></span>选择图片</a>
        <a href="javascript:void(0)" class="btn btn-warning btn-sm" data-dismiss="modal">关闭</a>
      </div>
      
    </div>﻿<!-- modal-content -->
  </div><!-- modal-dialog -->
</div><!-- modal fade -->